# 1D array && 2D array
_ __

In [2]:
import numpy as np
# creating 2D array
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
n = np.array([(1,2,3),(4,5,6)])
n

In [ ]:
m = np.array([[1,2,33],(23,45,67)])
m

In [ ]:
b = np.array([[2,3,4,12],[5,6,7,13],[8,9,0,15]]) # if two square brackets in the parenthesis of the array thn it is know as 2d array
b

array([[ 2,  3,  4, 12],
       [ 5,  6,  7, 13],
       [ 8,  9,  0, 15]])

In [31]:
#Array attributes
# shape - return the shape of the array(no of rows, no. of columns) 

b.shape

(3, 4)

In [ ]:
b.size # rows * columns

12

In [7]:
# ndim - finds the no. of dimension of the array
b.ndim

2

In [8]:
a= np.array([[[[[1,2,4]]]]])
a.ndim

5

In [ ]:
# we can take the dimension max upto 32 or 64 based on operation 
a = np.array([1,2,3],ndim=64)
a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,
                                                                      2,
                                                                      3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [ ]:
# print(np.MAXDIMS)


In [10]:
# arange = it returns a 1d array of given range
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2) # (start, stops, step)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(10,0,-2)

In [ ]:
print(np.zeros(5)) # give all the elements zeros and by default dtype is float

[0. 0. 0. 0. 0.]


In [17]:
np.zeros((5,5), dtype = 'int')
np.zeros((5,5), dtype = int)
# np.zeros((5,5)).astype =(int)
# np.identity(5)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((10,10),dtype=int) # gives all element is 1
print()

In [19]:
# full - return a matrix filled with with a specific character 
np.full((5,5), 8)
np.full((5,5), '♾️')

array([['♾️', '♾️', '♾️', '♾️', '♾️'],
       ['♾️', '♾️', '♾️', '♾️', '♾️'],
       ['♾️', '♾️', '♾️', '♾️', '♾️'],
       ['♾️', '♾️', '♾️', '♾️', '♾️'],
       ['♾️', '♾️', '♾️', '♾️', '♾️']], dtype='<U2')

In [32]:
# eye = identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# linspace = return equally distrbuted number
# np.linspace(0,100,10)
np.linspace(1,100,11, dtype= int)

array([  1,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [34]:
#Random Numbers 
#returns a random value between 0 & 1 
np.random.rand(3,4)
print(np.random.randint(1,100, (3,3))) # it includes the lower value and excludes the higher value returns a random integer value from the given range 
print(np.random.randint(1,20, size = 8))

# # syntax: 
# np.random.randint(num1,num2, (rows,coloumns))


[[82 78 77]
 [47 40  6]
 [72 78 95]]
[18  7  9 18 19 12  1  8]


# Mathmatical Functions
___

In [ ]:
a = np.array([23,75,57,50,81])
b = np.array([4,8,6,5,9])

In [ ]:
a+b

In [ ]:
#add = addition
np.add(a,b)

In [ ]:
#subtact = subtraction
np.subtract(a,b)

In [ ]:
# multiply = Multiplication
np.multiply(a,b)

In [ ]:
#divide = division
np.divide(a,b)
n

In [ ]:
#floor_divide
print(np.floor_divide(a,b))
#mod = modulo
print(np.mod(a,b))

In [ ]:
#divmod - floor_division and mod
np.divmod(a,b)

In [ ]:
# log = by default with base'e'
np.log10(a)

In [ ]:
#sqrt = square root
np.sqrt(a)

In [ ]:
#cbrt = cube root
np.cbrt(a)

In [ ]:
#power = exponent
np.power(b,2)

In [ ]:
#Trigonometry = here it return the valueb
#sin
np.sin(a)

In [ ]:
np.sin(90)#radians

In [ ]:
np.sin(90*(np.pi/180))#in degrees

In [ ]:
#cos
np.cos(a)

In [ ]:
#tan 
np.tan(a)

In [ ]:
#cot
1/np.tan(a)

# STATISTICAL FUNCTION
___

In [6]:
a= np.array([45,67,20,58,25])
a

array([45, 67, 20, 58, 25])

In [ ]:
#np.max = return maximum value
print(np.max(a))

In [ ]:
#np.min = return minimum value
print(np.min(a))

In [ ]:
#argmax= returns index position of maximum value 
np.argmax(a)

In [ ]:
#argmin = returns the min value index position
np.argmin(a)

In [7]:
#sort = (ascending order)
print(np.sort(a))

[20 25 45 58 67]


In [8]:
#argsort (return index position in ascending order)
print(np.argsort(a))

[2 4 0 3 1]


In [ ]:
a

In [9]:
#flip 
np.flip(a)


array([25, 58, 20, 67, 45])

In [ ]:
# to get in decensing order sort it and flip it
np.flip(np.sort(a))

In [ ]:
#mean 
print(np.mean(a))

In [ ]:
# median
print(np.median(a))

In [ ]:
#std = standard deviation
print(np.std(a))

In [ ]:
#var = varinace 
print(np.var(a))

In [ ]:
#cumsum = cumulative summation
np.cumsum(b)

In [ ]:
#cumprod = cumulative product
print(np.cumprod(b))

In [ ]:
a = np.array([23,75,57,50,81])
b = np.array([4,8,6,5,9])

In [10]:
#repeat = reapet each elements for the given no. of 
a = np.array([1,2,3,4])
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [12]:
#tiles = repeats whole sequence for given no. b

np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [13]:
#where 
a = np.array([1,2,4,3,4,5,3,4,4,6,4])
np.where(a==4)

(array([ 2,  4,  7,  8, 10]),)

In [ ]:
# np.round = round of the number
print(np.round(24.6))

In [ ]:
#celling

print(np.ceil(25.1))
#trunk
print(np.trunc(22.9))