# VECTOR MATHS
___

In [1]:
import numpy as np

In [2]:
a = np.array([[1,3],[2,4]])
b= np.array([[5,7],[6,9]])

print(a)
print(b)

[[1 3]
 [2 4]]
[[5 7]
 [6 9]]


In [3]:
# dot = dot product  
# @ is work as dot product
print(a@b)
print(np.dot(a,b))


[[23 34]
 [34 50]]
[[23 34]
 [34 50]]


# CROSS PRODUCT

In [ ]:

np.cross(a,b)

C:\Users\ksaby\AppData\Local\Temp\ipykernel_10828\3878451386.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


array([-8, -6])

# TRANSPOSE

In [ ]:

np.transpose(a)

array([[1, 2],
       [3, 4]])

# indexing and slicing in 1D array

In [ ]:

a = np.array([45,78,25,99,66])
a

array([45, 78, 25, 99, 66])

# indexing 
# syntax: var[index_position]

In [ ]:

print(a[2])
print(a[-3])

25
25


# slicing

In [ ]:

print(len(a))
print(a[::2])


5
[45 25 66]


# indexing and slicing in 2Darray

In [ ]:

b = np.random.randint(1,20,(5,5))
print(b)

[[ 7  9  4  3 16]
 [17 14 18  5  6]
 [18 19 17 10  1]
 [14  3  4  3 13]
 [ 6 18 12 11  6]]


# Indexing 
# syntax : var[row_index,col_index]

In [ ]:

b[3,2]

np.int32(4)

In [11]:
b[3] # by default row

array([14,  3,  4,  3, 13], dtype=int32)

# to find the rrow and col index position of an

In [ ]:

print(np.where(b==4))

(array([0, 3]), array([2, 2]))


# slicing
# syntax: var[row_slicing, col_slicing]

In [ ]:

print(b[1:4:1, 1:4:1])

[[14 18  5]
 [19 17 10]
 [ 3  4  3]]


In [14]:
# concatination 
a = np.random.randint(1,20,(2,2))
b = np.random.randint(1,20,(2,4))
c = np.random.randint(1,20,(4,4))
print(a)
print()
print(b)
print()
print(c)

[[11 16]
 [15 17]]

[[ 5 17  9  1]
 [10  8  6 15]]

[[ 2 10 13  7]
 [ 4  7  7 12]
 [ 2 18 15 18]
 [ 5  5 13 13]]


# axis = 1 (horizontal wise)

In [ ]:

np.concatenate((a,b), axis=1)

array([[11, 16,  5, 17,  9,  1],
       [15, 17, 10,  8,  6, 15]], dtype=int32)

# axis = 0 (coloumn wise) (by default)

In [ ]:

print(np.concatenate((b,c), axis = 0))

[[ 5 17  9  1]
 [10  8  6 15]
 [ 2 10 13  7]
 [ 4  7  7 12]
 [ 2 18 15 18]
 [ 5  5 13 13]]


# stack = joining matrix
# hstack - Horizontal stack

In [ ]:

np.hstack((a,b))

array([[11, 16,  5, 17,  9,  1],
       [15, 17, 10,  8,  6, 15]], dtype=int32)

# vstack = vertical stack

In [ ]:

np.vstack((b,c))

array([[ 5, 17,  9,  1],
       [10,  8,  6, 15],
       [ 2, 10, 13,  7],
       [ 4,  7,  7, 12],
       [ 2, 18, 15, 18],
       [ 5,  5, 13, 13]], dtype=int32)

# concatenation - joining the martrix

In [ ]:

a=np.random.randint(1,20,(2,2))
b= np.random.randint(1,20,(2,2))
print(a)
print(b)
 

[[13  6]
 [ 3 12]]
[[ 3 13]
 [18  2]]


In [20]:
np.stack((a,b), axis=-1) # its a 3D array

array([[[13,  3],
        [ 6, 13]],

       [[ 3, 18],
        [12,  2]]], dtype=int32)

# diagonal 

In [ ]:

x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.diagonal(x)

array([1, 5, 9])

In [23]:
print(np.flip(x))
print()
print(np.flip(x,axis = 0))
print()
print(np.flip(x, axis = 1))
print()
print(np.diag(np.flip(x,axis=1)))
print()
np.flip(np.eye(5,dtype=int),axis=1)

[[9 8 7]
 [6 5 4]
 [3 2 1]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]

[3 5 7]



array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

# PANDAS 
___

In [24]:
# PANDAS 
""" 
Pandas is a python library which is use to analyze and manipulate the data.
we cam read and create datasets using pandas.

Pandas is of two type :-
--> Series (single coloums)
--> Dataframe (multiple columns)
"""
import pandas as pd
print("okay")

# creating series
# list to series
s = pd.Series(['a','b','c','d','e'])
print(type(s))
print(s)

okay
<class 'pandas.core.series.Series'>
0    a
1    b
2    c
3    d
4    e
dtype: object


In [25]:
# s = pd.Series(['a','b','c','d','e'],index=np.arange(5,10))

s = pd.Series(['a','b','c','d','e'],index=[10,20,30,40,50])
print(s)

10    a
20    b
30    c
40    d
50    e
dtype: object


In [26]:
#indexing
s[20]

'b'

In [27]:
# slicing
s[0:4:2]

10    a
30    c
dtype: object

# Tuple to series


In [ ]:

t= pd.Series((100,200,300,400),index= [10,20,30,40])
print(t)
t[::2]

10    100
20    200
30    300
40    400
dtype: int64


10    100
30    300
dtype: int64

# set to series

In [ ]:

# we can not create a Series using set as it is unorderd
    s = pd.Series({12,12,12,34,34,45,45,25})
s

IndentationError: unexpected indent (2705535099.py, line 3)

# Dictionary to Series

In [ ]:

d = pd.Series({'a':1, 'b':2, 'c':3,'d':4})
d
d1= pd.Series({'a':1, 'b':2, 'c':3,'d':4}, index=['e','f','a','h'])
d1

# we cant change the index position in case of dict as the key are used as index

In [ ]:
# indexing
d1['c']

In [ ]:
#slicing
d[::1]